apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Route66
  description: TerraCore Pipeline
  tags:
    - go
    - terraform
    - groovy
spec:
  type: pipeline
  lifecycle: production
  owner: app-teams
